# Generated by Django 3.0.4 on 2020-03-24 19:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=64)),
                ('document_type', models.CharField(choices=[('RG', 'Registro civil / NUIP'), ('TI', 'Tarjeta de identidad'), ('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('PA', 'Passport')], max_length=2)),
                ('document_id', models.CharField(max_length=16)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Patient')),
            ],
        ),
    ]
