# Generated by Django 3.0.4 on 2020-03-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('order', models.IntegerField()),
                ('text', models.CharField(max_length=512)),
                ('item_type', models.CharField(choices=[('group', 'group'), ('display', 'display'), ('boolean', 'boolean'), ('decimal', 'decimal'), ('integer', 'integer'), ('date', 'date'), ('dateTime', 'dateTime')], max_length=12)),
                ('required', models.BooleanField()),
                ('max_length', models.IntegerField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='definitions.Questionnaire')),
            ],
        ),
    ]
