# Generated by Django 3.0.5 on 2020-04-01 20:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0002_auto_20200328_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireitem',
            name='choices',
            field=jsonfield.fields.JSONField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireitem',
            name='item_type',
            field=models.CharField(choices=[('group', 'group'), ('display', 'display'), ('string', 'string'), ('text', 'text'), ('boolean', 'boolean'), ('radiogroup', 'radiogroup'), ('decimal', 'decimal'), ('integer', 'integer'), ('date', 'date'), ('dateTime', 'dateTime')], max_length=12),
        ),
        migrations.AlterField(
            model_name='questionnaireitem',
            name='max_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
