# Generated by Django 3.0.4 on 2020-03-28 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.IntegerField()),
                ('authored', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('value', models.CharField(max_length=256)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.QuestionnaireResponse')),
            ],
        ),
    ]
