# Generated by Django 3.0.4 on 2020-03-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0002_auto_20200328_2222'),
        ('events', '0002_questionnaireresponse_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='definitions.Questionnaire'),
        ),
    ]
