# Generated by Django 3.0.4 on 2020-03-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmetadata',
            name='inputs',
            field=models.ManyToManyField(to='models.ModelParameter'),
        ),
    ]
