# Generated by Django 3.0.4 on 2020-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_modelmetadata_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmetadata',
            name='outputs',
            field=models.ManyToManyField(related_name='outputs', to='models.ModelParameter'),
        ),
        migrations.AlterField(
            model_name='modelmetadata',
            name='inputs',
            field=models.ManyToManyField(related_name='inputs', to='models.ModelParameter'),
        ),
    ]
